#The database

- name: Load the docker database image
  docker_container:
    name: database
    image: alexislaf/smplstuddb:1.0
    networks:
      - name: database 
    env:
    # Set the password to the variable db_pwd.
      POSTGRES_PASSWORD : "{{ db_pwd }}"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    state: started
    restart: true
    