all:
 vars:
   ansible_user: admin
   ansible_ssh_private_key_file: /home/runner/work/Docker/Docker/Ansible/vaulted_key
   # The path to the private key file inside the wsl used to run the commands
 children:
   prod:
     hosts: alexis.lafargue.takima.school
     #The host to be connected to