# Build stage
FROM eclipse-temurin:23-jdk-alpine AS myapp-build
ENV MYAPP_HOME=/opt/myapp
WORKDIR $MYAPP_HOME

RUN apk add --no-cache maven

COPY pom.xml .
COPY src ./src
RUN mvn dependency:go-offline package -DskipTests=true

# Run stage
FROM eclipse-temurin:23-jre-alpine
ENV MYAPP_HOME=/opt/myapp \
    POSTGRES_PASSWORD=pwd
WORKDIR $MYAPP_HOME
COPY --from=myapp-build $MYAPP_HOME/target/*.jar $MYAPP_HOME/myapp.jar

ENTRYPOINT java -jar myapp.jar -POSTGRES_PASSWORD=$POSTGRES_PASSWORD

