name: Ansible deployment

on:
  image_version:
    names:
      - "alexislaf/javabackend"
      - "alexislaf/httpproxy"
      - "alexislaf/smplstuddb"
    versions:
      - 1.*
      - 2.*
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'
    branches: [main]

jobs:

  ansible_deploy :

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        sparse-checkout: /Ansible
    
    - name: Install Ansible
      uses: rishabhc32/install-ansible@v1.2.2

    - name: decrypt vaulted-key
      shell: bash
      with: # Set the secret as an input
        vault_key : ${{ secrets.ANSIBLE_VAULT_PWD }}
      run: |
        touch vaultkey 
        echo '${{ vault_key }}' >> vaultkey
        ansible-vault decrypt --vault-password-file vaultkey

    - name: Run deploy
      run: ansible-playbook -i inventories/cdsetup.yml playbook.yml 
