# The proxy serving http to the user.

- name: Load the docker proxy image
  docker_container:
    name: proxy
    image: alexislaf/httpproxy:1.0
    networks:
      - name: api
      - name: front 
    ports: 
    # Open the proxy's port 8080 to the internet
      - "8080:80"
    state: started
    restart: true
