name: Ansible deployment

on:
  image_version:
    names:
      - "alexislaf/javabackend"
      - "alexislaf/httpproxy"
      - "alexislaf/smplstuddb"
    versions:
      - 1.*
      - 2.*
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

jobs:

  ansible_deploy :

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        sparse-checkout: Ansible
    
    - name: Install Ansible
      uses: rishabhc32/install-ansible@v1.2.2

    #- name: decrypt vaulted-key
     # shell: bash
      #run: |
      #  touch vaultkey 
      #  echo '${{ secrets.ANSIBLE_VAULT_PWD }}' >> vaultkey
      #  ansible-vault decrypt --vault-password-file vaultkey

    - name: Run deploy
      run: ansible-playbook -i inventories/cdsetup.yml playbook.yml 
